insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (112, 'Belarus', 'BY', 'BLR', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (608, 'Philippines', 'PH', 'PHL', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (504, 'Morocco', 'MA', 'MAR', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (417, 'Kyrgyzstan', 'KG', 'KGZ', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (004, 'Afghanistan', 'AF', 'AFG', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (558, 'Nicaragua', 'NI', 'NIC', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (250, 'France', 'FR', 'FRA', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (332, 'Haiti', 'HT', 'HTI', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (158, 'Taiwan, Province of China', 'TW', 'TWN', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (630, 'Puerto Rico', 'PR', 'PRI', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (132, 'Cape Verde', 'CV', 'CPV', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (262, 'Djibouti', 'DJ', 'DJI', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (136, 'Cayman Islands', 'KY', 'CYM', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (428, 'Latvia', 'LV', 'LVA', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (050, 'Bangladesh', 'BD', 'BGD', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (070, 'Bosnia and Herzegovina', 'BA', 'BIH', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (074, 'Bouvet Island', 'BV', 'BVT', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (591, 'Panama', 'PA', 'PAN', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (238, 'Falkland Islands (Malvinas)', 'FK', 'FLK', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (760, 'Syrian Arab Republic', 'SY', 'SYR', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (860, 'Uzbekistan', 'UZ', 'UZB', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (108, 'Burundi', 'BI', 'BDI', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (328, 'Guyana', 'GY', 'GUY', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (296, 'Kiribati', 'KI', 'KIR', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (484, 'Mexico', 'MX', 'MEX', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (124, 'Canada', 'CA', 'CAN', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (584, 'Marshall Islands', 'MH', 'MHL', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (352, 'Iceland', 'IS', 'ISL', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (312, 'Guadeloupe', 'GP', 'GLP', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (052, 'Barbados', 'BB', 'BRB', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (422, 'Lebanon', 'LB', 'LBN', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (426, 'Lesotho', 'LS', 'LSO', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (574, 'Norfolk Island', 'NF', 'NFK', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (638, 'Reunion', 'RE', 'REU', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (222, 'El Salvador', 'SV', 'SLV', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (438, 'Liechtenstein', 'LI', 'LIE', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (446, 'Macao', 'MO', 'MAC', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (092, 'Virgin Islands, British', 'VG', 'VGB', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (666, 'Saint Pierre and Miquelon', 'PM', 'SPM', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (663, 'Saint Martin (French part)', 'MF', 'MAF', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (140, 'Central African Republic', 'CF', 'CAF', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (180, 'Congo, the Democratic Republic of the', 'CD', 'COD', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (705, 'Slovenia', 'SI', 'SVN', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (500, 'Montserrat', 'MS', 'MSR', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (854, 'Burkina Faso', 'BF', 'BFA', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (496, 'Mongolia', 'MN', 'MNG', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (320, 'Guatemala', 'GT', 'GTM', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (086, 'British Indian Ocean Territory', 'IO', 'IOT', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (626, 'Timor-Leste', 'TL', 'TLS', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (818, 'Egypt', 'EG', 'EGY', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (260, 'French Southern Territories', 'TF', 'ATF', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (554, 'New Zealand', 'NZ', 'NZL', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (024, 'Angola', 'AO', 'AGO', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (275, 'Palestinian Territory, Occupied', 'PS', 'PSE', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (703, 'Slovakia', 'SK', 'SVK', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (654, 'Saint Helena', 'SH', 'SHN', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (300, 'Greece', 'GR', 'GRC', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (462, 'Maldives', 'MV', 'MDV', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (764, 'Thailand', 'TH', 'THA', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (804, 'Ukraine', 'UA', 'UKR', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (612, 'Pitcairn', 'PN', 'PCN', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (776, 'Tonga', 'TO', 'TON', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (368, 'Iraq', 'IQ', 'IRQ', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (380, 'Italy', 'IT', 'ITA', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (162, 'Christmas Island', 'CX', 'CXR', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (498, 'Moldova', 'MD', 'MDA', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (598, 'Papua New Guinea', 'PG', 'PNG', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (324, 'Guinea', 'GN', 'GIN', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (196, 'Cyprus', 'CY', 'CYP', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (208, 'Denmark', 'DK', 'DNK', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (414, 'Kuwait', 'KW', 'KWT', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (166, 'Cocos (Keeling) Islands', 'CC', 'CCK', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (876, 'Wallis and Futuna', 'WF', 'WLF', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (288, 'Ghana', 'GH', 'GHA', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (586, 'Pakistan', 'PK', 'PAK', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (184, 'Cook Islands', 'CK', 'COK', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (266, 'Gabon', 'GA', 'GAB', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (652, 'Saint Barthelemy', 'BL', 'BLM', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (499, 'Montenegro', 'ME', 'MNE', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (051, 'Armenia', 'AM', 'ARM', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (226, 'Equatorial Guinea', 'GQ', 'GNQ', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (191, 'Croatia', 'HR', 'HRV', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (831, 'Guernsey', 'GG', 'GGY', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (120, 'Cameroon', 'CM', 'CMR', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (384, 'Cote d Ivoire', 'CI', 'CIV', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (716, 'Zimbabwe', 'ZW', 'ZWE', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (752, 'Sweden', 'SE', 'SWE', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (688, 'Serbia', 'RS', 'SRB', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (233, 'Estonia', 'EE', 'EST', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (566, 'Nigeria', 'NG', 'NGA', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (474, 'Martinique', 'MQ', 'MTQ', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (670, 'Saint Vincent and the Grenadines', 'VC', 'VCT', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (175, 'Mayotte', 'YT', 'MYT', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (068, 'Bolivia', 'BO', 'BOL', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (090, 'Solomon Islands', 'SB', 'SLB', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (430, 'Liberia', 'LR', 'LBR', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (795, 'Turkmenistan', 'TM', 'TKM', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (796, 'Turks and Caicos Islands', 'TC', 'TCA', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (404, 'Kenya', 'KE', 'KEN', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (258, 'French Polynesia', 'PF', 'PYF', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (604, 'Peru', 'PE', 'PER', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (212, 'Dominica', 'DM', 'DMA', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (454, 'Malawi', 'MW', 'MWI', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (788, 'Tunisia', 'TN', 'TUN', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (678, 'Sao Tome and Principe', 'ST', 'STP', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (156, 'China', 'CN', 'CHN', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (270, 'Gambia', 'GM', 'GMB', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (239, 'South Georgia and the South Sandwich Islands', 'GS', 'SGS', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (800, 'Uganda', 'UG', 'UGA', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (768, 'Togo', 'TG', 'TGO', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (690, 'Seychelles', 'SC', 'SYC', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (736, 'Sudan', 'SD', 'SDN', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (470, 'Malta', 'MT', 'MLT', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (044, 'Bahamas', 'BS', 'BHS', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (116, 'Cambodia', 'KH', 'KHM', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (780, 'Trinidad and Tobago', 'TT', 'TTO', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (894, 'Zambia', 'ZM', 'ZMB', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (056, 'Belgium', 'BE', 'BEL', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (660, 'Anguilla', 'AI', 'AIA', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (364, 'Iran, Islamic Republic of', 'IR', 'IRN', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (214, 'Dominican Republic', 'DO', 'DOM', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (178, 'Congo', 'CG', 'COG', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (620, 'Portugal', 'PT', 'PRT', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (834, 'Tanzania, United Republic of', 'TZ', 'TZA', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (344, 'Hong Kong', 'HK', 'HKG', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (466, 'Mali', 'ML', 'MLI', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (218, 'Ecuador', 'EC', 'ECU', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (360, 'Indonesia', 'ID', 'IDN', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (418, 'Lao Peoples Democratic Republic', 'LA', 'LAO', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (442, 'Luxembourg', 'LU', 'LUX', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (152, 'Chile', 'CL', 'CHL', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (434, 'Libyan Arab Jamahiriya', 'LY', 'LBY', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (048, 'Bahrain', 'BH', 'BHR', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (807, 'Macedonia, the former Yugoslav Republic of', 'MK', 'MKD', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (242, 'Fiji', 'FJ', 'FJI', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (570, 'Niue', 'NU', 'NIU', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (694, 'Sierra Leone', 'SL', 'SLE', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (882, 'Samoa', 'WS', 'WSM', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (583, 'Micronesia, Federated States of', 'FM', 'FSM', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (408, 'Korea, Democratic Peoples Republic of', 'KP', 'PRK', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (512, 'Oman', 'OM', 'OMN', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (792, 'Turkey', 'TR', 'TUR', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (581, 'United States Minor Outlying Islands', 'UM', 'UMI', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (562, 'Niger', 'NE', 'NER', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (530, 'Netherlands Antilles', 'AN', 'ANT', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (203, 'Czech Republic', 'CZ', 'CZE', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (148, 'Chad', 'TD', 'TCD', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (316, 'Guam', 'GU', 'GUM', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (508, 'Mozambique', 'MZ', 'MOZ', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (204, 'Benin', 'BJ', 'BEN', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (642, 'Romania', 'RO', 'ROU', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (254, 'French Guiana', 'GF', 'GUF', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (012, 'Algeria', 'DZ', 'DZA', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (450, 'Madagascar', 'MG', 'MDG', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (840, 'United States', 'US', 'USA', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (084, 'Belize', 'BZ', 'BLZ', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (174, 'Comoros', 'KM', 'COM', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (682, 'Saudi Arabia', 'SA', 'SAU', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (600, 'Paraguay', 'PY', 'PRY', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (372, 'Ireland', 'IE', 'IRL', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (643, 'Russian Federation', 'RU', 'RUS', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (170, 'Colombia', 'CO', 'COL', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (756, 'Switzerland', 'CH', 'CHE', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (887, 'Yemen', 'YE', 'YEM', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (548, 'Vanuatu', 'VU', 'VUT', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (458, 'Malaysia', 'MY', 'MYS', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (533, 'Aruba', 'AW', 'ABW', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (710, 'South Africa', 'ZA', 'ZAF', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (008, 'Albania', 'AL', 'ALB', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (674, 'San Marino', 'SM', 'SMR', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (040, 'Austria', 'AT', 'AUT', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (016, 'American Samoa', 'AS', 'ASM', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (492, 'Monaco', 'MC', 'MCO', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (478, 'Mauritania', 'MR', 'MRT', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (060, 'Bermuda', 'BM', 'BMU', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (348, 'Hungary', 'HU', 'HUN', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (010, 'Antarctica', 'AQ', 'ATA', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (480, 'Mauritius', 'MU', 'MUS', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (032, 'Argentina', 'AR', 'ARG', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (616, 'Poland', 'PL', 'POL', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (772, 'Tokelau', 'TK', 'TKL', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (268, 'Georgia', 'GE', 'GEO', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (100, 'Bulgaria', 'BG', 'BGR', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (276, 'Germany', 'DE', 'DEU', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (578, 'Norway', 'NO', 'NOR', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (392, 'Japan', 'JP', 'JPN', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (784, 'United Arab Emirates', 'AE', 'ARE', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (192, 'Cuba', 'CU', 'CUB', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (520, 'Nauru', 'NR', 'NRU', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (188, 'Costa Rica', 'CR', 'CRI', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (762, 'Tajikistan', 'TJ', 'TJK', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (336, 'Holy See (Vatican City State)', 'VA', 'VAT', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (144, 'Sri Lanka', 'LK', 'LKA', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (356, 'India', 'IN', 'IND', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (304, 'Greenland', 'GL', 'GRL', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (686, 'Senegal', 'SN', 'SEN', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (400, 'Jordan', 'JO', 'JOR', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (232, 'Eritrea', 'ER', 'ERI', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (516, 'Namibia', 'NA', 'NAM', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (410, 'Korea, Republic of', 'KR', 'KOR', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (104, 'Myanmar', 'MM', 'MMR', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (858, 'Uruguay', 'UY', 'URY', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (020, 'Andorra', 'AD', 'AND', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (659, 'Saint Kitts and Nevis', 'KN', 'KNA', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (646, 'Rwanda', 'RW', 'RWA', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (662, 'Saint Lucia', 'LC', 'LCA', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (234, 'Faroe Islands', 'FO', 'FRO', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (748, 'Swaziland', 'SZ', 'SWZ', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (832, 'Jersey', 'JE', 'JEY', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (076, 'Brazil', 'BR', 'BRA', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (862, 'Venezuela', 'VE', 'VEN', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (732, 'Western Sahara', 'EH', 'ESH', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (634, 'Qatar', 'QA', 'QAT', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (798, 'Tuvalu', 'TV', 'TUV', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (724, 'Spain', 'ES', 'ESP', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (248, 'Aland Islands', 'AX', 'ALA', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (585, 'Palau', 'PW', 'PLW', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (064, 'Bhutan', 'BT', 'BTN', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (376, 'Israel', 'IL', 'ISR', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (096, 'Brunei Darussalam', 'BN', 'BRN', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (031, 'Azerbaijan', 'AZ', 'AZE', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (524, 'Nepal', 'NP', 'NPL', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (231, 'Ethiopia', 'ET', 'ETH', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (340, 'Honduras', 'HN', 'HND', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (744, 'Svalbard and Jan Mayen', 'SJ', 'SJM', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (704, 'Viet Nam', 'VN', 'VNM', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (036, 'Australia', 'AU', 'AUS', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (334, 'Heard Island and McDonald Islands', 'HM', 'HMD', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (580, 'Northern Mariana Islands', 'MP', 'MNP', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (528, 'Netherlands', 'NL', 'NLD', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (292, 'Gibraltar', 'GI', 'GIB', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (706, 'Somalia', 'SO', 'SOM', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (540, 'New Caledonia', 'NC', 'NCL', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (028, 'Antigua and Barbuda', 'AG', 'ATG', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (833, 'Isle of Man', 'IM', 'IMN', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (246, 'Finland', 'FI', 'FIN', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (440, 'Lithuania', 'LT', 'LTU', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (740, 'Suriname', 'SR', 'SUR', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (388, 'Jamaica', 'JM', 'JAM', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (826, 'United Kingdom', 'GB', 'GBR', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (308, 'Grenada', 'GD', 'GRD', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (850, 'Virgin Islands, U.S.', 'VI', 'VIR', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (702, 'Singapore', 'SG', 'SGP', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (624, 'Guinea-Bissau', 'GW', 'GNB', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (072, 'Botswana', 'BW', 'BWA', 1);
insert into up_country(ID, NAME, ALPHA2, ALPHA3,  ACTIVE) values (398, 'Kazakhstan', 'KZ', 'KAZ', 1);
